[[manager.prepend_keymap]]
# Mnemonic: "Go to [d]ownloads"
on   = ["g", "d"]
run  = "cd ~/Downloads"
desc = "Go to the downloads directory"

[[manager.prepend_keymap]]
on   = "<C-z>"
run  = "quit"
desc = "quit"

[[manager.prepend_keymap]]
on   = "<C-o>"
run  = "back"
desc = "back"

[[manager.prepend_keymap]]
on   = "f"
run  = "filter --smart"
desc = "filter"
